### ISSUE TITLE
Change sequence on diagram

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_image_pick_11#1]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/5799860/180229974-9da2d774-1000-4586-ae14-9a78f05cade7.png">

**Comment by caitlynbakery** [comment]
![Screen Shot 2022-07-21 at 7 32 22 AM](https://user-images.githubusercontent.com/22283010/180240558-25d5d9db-41a0-42bb-8fdb-7f3d2d4f47b2.png)

View my commit [here](8d6c7ed94125f6afe6252743165d2f8047587a3f)
